### PR TITLE
Add DuckDB and MonetDBLite notebooks

### PR DESCRIPTION
**Pull request by nnistelrooij**

### CODE REVIEW

**Comment by nnistelrooij** [comment]
# BM25 + Term Proximity in DuckDB and MonetDBLite
I tested the algorithm from Rasolofo in MonetDBLite and DuckDB and found some interesting things. The query used is 'new york'.

## DuckDB

### BM25 -> Term Proximity
First the documents are scored based on Okapi BM25. The top 20 documents are then used in the Term Proximity to give the results to the user. The query takes about 7.2s to complete and the top 5 results are in the table below. The results are good, as you can see by the high scores.

| docid  | score      | 
|--------|-----------| 
| 50961  | 55.958108 | 
| 84012  | 45.879320 | 
| 53470  | 42.451083 | 
| 134713 | 29.642062 | 
| 118643 | 18.188489 | 

### Term Proximity
All the documents can also be scored based on Rasolofo's algorithm. This query takes about 3.7s to complete. See the top 5 results in the below table. The results are very bad; only one of the docs in the top table is in this table. Another strange phenomenon is that the query takes less time to complete, while the number of documents scored is far greater (3808 vs 20).

| docid  | score      | 
|--------|-----------| 
| 50961  | 55.958108 | 
| 19577  | 16.473072 | 
| 181752 | 13.586938 | 
| 139362 | 13.327779 | 
| 238507 | 12.143474 | 

When joining this scores table with the top k docs from BM25 we get this table. Somehow, 16 of the 20 top documents are dropped somewhere along the way. The query time is 5.5s.

| docid  | score      | 
|--------|-----------| 
| 50961  | 55.958108 | 
| 181752 | 13.586938 | 
| 119535 | 0.638042  | 
| 250569 | 0.152059  |

When constraining the range of docids of the scores table between 50961 and 84012, the top 3 results retrieved in the first table **are** present. The query time is now 4.1s.

| docid | score      | 
|-------|-----------| 
| 50961 | 55.958108 | 
| 84012 | 45.879320 | 
| 53470 | 42.451083 | 
| 83427 | 21.030780 | 
| 51576 | 17.030353 | 

When both joining the scores table with the top k BM25 docs and constraining the docids, we get this table. The top 3 docs **are** there now! 

| docid | score      | 
|-------|-----------| 
| 50961 | 55.958108 | 
| 84012 | 45.879320 | 
| 53470 | 42.451083 | 
| 51576 | 17.030353 | 

So there seems to be some bug with DuckDB. First doing BM25 and then Term Proximity does work, but takes an awful long time and doing Term Proximity for all docs doesn't work

## MonetDBLite

### BM25 -> Term Proximity
First the documents are scored based on Okapi BM25. The top 20 documents are then used in the Term Proximity to give the results to the user. The query takes about 0.33s to complete and the top 5 results are in the table below. The results are good, as you can see by the high scores. The same documents are retrieved as with DuckDB, but the scores are larger for some reason.

| docid  | score        | 
|--------|------------| 
| 50961  | 128.848305 | 
| 84012  | 105.641038 | 
| 53470  | 97.747231  | 
| 134713 | 68.253371  | 
| 118643 | 41.880545  | 

### Term Proximity
All the documents can also be scored based on Rasolofo's algorithm. This query takes about 0.58s to complete. See the top 5 results in the below table. The results are almost the same as above. Document 18841 was not retrieved by BM25, but is retrieved here. But the score is higher, so that was to be expected. As expected, computing the Term Proximity score for all documents takes longer than just the top 20 Okapi BM25 documents. MonetDBLite scores more documents than DuckDB (19470 vs. 3808). So somewhere in the difference of these numbers, the good documents are dropped by DuckDB.

| docid  | score        | 
|--------|------------| 
| 50961  | 128.848305 | 
| 84012  | 105.641038 | 
| 53470  | 97.747231  | 
| 134713 | 68.253371  | 
| 18841  | 52.145487  |

**Comment by rusane** [comment]
Do you think it is possible to put the database querying code into a separate function? I believe that would be more convenient for timing and evaluation (especially when we want to test multiple queries). We only have to then call that function and change the query parameter each time.

Something like this:
```python
# Example query: q = "blue wizard hat"
def search(c, q):
  '''
  Args:
    c: cursor of DuckDB 
    q: query string
  '''
  query_words = q.split() # ["blue", "wizard", "hat"]
  len_query = make_query(c, *query_words) # unpack query words
  ... # code that is already there either with or without term proximity
```

Also, do you know if the relevance judgements can be retrieved at the same time in the tables? E.g.,

docid | score | relevance
-|-|-
12345 | 100 | 1
... | ... | ...
98765 | 10 | 0

We will need those relevance judgements for the evaluation to compute the Average Precision and/or MAP.

**Comment by nnistelrooij** [comment]
### Function
I will definitely make such a function. You can then easily add the options in the function parameters (DuckDB vs. MonetDBLite, conjunctive vs. disjunctive queries, first Okapi BM25 vs. first KLD, add Rasolofo term proximity, max number of retrieved documents, the hyper-parameters, whether to sum the first scores and term proximity scores, the span of a term pair for the term proximity algorithm, etc.). That will be the goal for the coming week.

### Relevance Judgements
The qrels can be added to the tables. The qrels are given as:

| queryid | docname | rel |
|----------|-----------|----|
| 309       | LA-4563  | 1   |

So I would have to have the queryid alongside the query to do that. This can be done by modifying the Robust04 test data, which can be found [here](https://trec.nist.gov/data/robust/04.testset.gz). The queryid-query pairs can be taken out with regex. This will be the goal for the week of 25 November.

If I have enough time, which I doubt, I could also implement (M)AP and (N)DCG in SQL. That way, you run one (enormous [which it kind of is already]) SQL query and immediately get the score for the whole dataset (or one query at a time).

**Comment by nnistelrooij** [comment]
#11 

Is this what you meant with the function? I've gone a bit overboard with all the options, but this does make it easier to compare: only Okapi BM25, only KLD, only Rasolofo, Okapi BM25 + Rasolofo, and KLD + Rasolofo with both DuckDB and MonetDBLite.

Let me know if you want any more options (I couldn't think of more).

**Comment by rusane** [comment]
Yes, that's fantastic! We only need the *qrels* now to perform the evaluation with MAP.

 Is the plan to add the *qrels* after retrieving the ranked list? Assuming that *qrels* can be loaded into a separate table, we can join the ranked list and *qrels* on `docname` or `docid` perhaps and then only those rows that have the corresponding *queryid*. We somehow have to preserve the ranking of the documents though. My SQL is not that great so I'm not sure how feasible this is. 
Adding *qrels* during retrieval is probably not a good idea as it will affect run time performance, which invalidates the time evaluation, unless we add a flag to the retrieval function that controls this (i.e., when timing the retrieval, set the flag to 0 so that no *qrels* are added in order to rule out the cost of adding *qrels*).

The *qrels* can possibly be found [here](https://trec.nist.gov/data/qrels_eng/index.html) for the Robust04 data set and we have to combine it like you said with [this](https://trec.nist.gov/data/topics_eng/index.html) (first item in the list of both links is for Robust04) to match *query* and *queryid*. I'm further assuming that the "topics" they are talking about are the queries.

**Pull request merged**
